services:
  test:
    platform: linux/amd64
    image: registry.gitlab.corp.paymaya.com/core/growth/messaging-platform/communications-mesh-team/hedwig-console-fe:v1.0.4
    build:
      context: .
      dockerfile: Dockerfile.Local
      args:
        REACT_APP_NODE_ENV: test
    volumes:
      - '.:/hedwig_console_fe'
      - '/hedwig_console_fe/node_modules'
    ports:
      - 8080:80

# pull docker image from container registry
# docker login registry.gitlab.corp.paymaya.com
# docker pull registry.gitlab.corp.paymaya.com/core/growth/messaging-platform/communications-mesh-team/hedwig-console-fe:v1.0.4

# running a docker container
# docker run -d -p 80:80 registry.gitlab.corp.paymaya.com/core/growth/messaging-platform/communications-mesh-team/hedwig-console-fe:hc-app-staging-v1.1.1